config/routes.rb
Rails.application.routes.draw do

  root 'salons#index'
  resources :salons
  resources :searches
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/salon.rb
class Salon < ApplicationRecord
  has_one_attached :image

  self.inheritance_column = "not_sti"

    def self.search(search)
        if search
            where(["name LIKE ?","%#{search}%"])
        else
            all
        end
    end

end

app/models/search.rb
class Search < ApplicationRecord

  self.inheritance_column = "not_sti"

  def search_salon
    salon = Salon.all
    salon = salon.where(['name LIKE ?', name]) if name.present?
    salon = salon.where(['address LIKE ?', address]) if address.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]

  # GET /salons
  # GET /salons.json
  def index
    @salons = Salon.search(params[:search])
  end

  # GET /salons/1
  # GET /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons
  # POST /salons.json
  def create
    @salon = Salon.new(salon_params)
    @salon.image.attach(salon_params[:image])

    respond_to do |format|
      if @salon.save
        format.html { redirect_to @salon, notice: '新規サロン登録されました。' }
        format.json { render :show, status: :created, location: @salon }
      else
        format.html { render :new }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salons/1
  # PATCH/PUT /salons/1.json
  def update
    @salon.image.purge
    @salon.image.attach(salon_params[:image])

    respond_to do |format|
      if @salon.update(salon_params)
        format.html { redirect_to @salon, notice: 'サロン情報の編集しました。' }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1
  # DELETE /salons/1.json
  def destroy
    @salon.destroy
    respond_to do |format|
      format.html { redirect_to salons_url, notice: 'サロン情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def salon_params
      params.require(:salon).permit(:name, :address, :phone, :comment, :tokio, :ie, :design, :straight, :image)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
    @search = Search.find(params[:id])
  end

  def new
    @search = Search.new
    @address = Salon.distinct.pluck(:address)
  end

  def create
    @search = Search.create(search_params)
    redirect_to @search
  end

  private

  def search_params
    params.require(:search).permit(:name, :address)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TokioTokyo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/salons/_form.html.erb
<%= form_with(model: salon, local: true) do |form| %>
  <% if salon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salon.errors.count, "error") %> prohibited this salon from being saved:</h2>

      <ul>
        <% salon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :tokio %>
    <%= form.check_box :tokio %>
  </div>

  <div class="field">
    <%= form.label :ie %>
    <%= form.check_box :ie %>
  </div>

  <div class="field">
    <%= form.label :design %>
    <%= form.check_box :design %>
  </div>

  <div class="field">
    <%= form.label :straight %>
    <%= form.check_box :straight %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salons/edit.html.erb
<h1>Editing Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Show', @salon %> |
<%= link_to 'Back', salons_path %>

app/views/salons/index.html.erb
<p id="notice"><%= notice %></p>


    <%= form_with(url: '/salons', method: 'get', local: true) do %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("検索") %>
    <%= link_to "戻る", '/salons' %>
    <% end %>

<%= link_to "Advanced Search", new_search_path %>
<h1>TOKIO INKARAMIを利用しているサロン一覧</h1>

<%= link_to 'サロン登録をする', new_salon_path, class: "btn btn-primary" %>

<p style="text-align:right;">店舗数: <%= Salon.all.count %></p>
<div class="row">
<% @salons.each do |salon| %>
<div class="card col-md-4" >
  <!-- <img class="card-img-top" src="..." alt="Card image cap"> -->
  <% if salon.image.attached? %>
    <p>
      <br>
      <%= image_tag salon.image, width: "100%", class: "salon-pic" %>
    </p>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= salon.name %></h5>
    <p class="card-text"><%= salon.comment %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><i class="fas fa-map-marker-alt"></i> <%= salon.address %></li>
    <li class="list-group-item"><i class="fas fa-phone-square"></i> <%= salon.phone %></li>
    <li class="list-group-item"><i class="fas fa-external-link-alt"></i> http://www._____.com</li>
  </ul>
  <h6 class="card-title">Menu</h6>
  <ul class="list_of_products">
    <li><% if salon.tokio == true %>
        Cut
        <% end %>
    </li>
    <li><% if salon.ie == true %>
        Shampoo
        <% end %>
    </li>
    <li><% if salon.design == true %>
        Color
        <% end %>
    </li>
    <li><% if salon.straight == true %>
        Perm
        <% end %>
    </li>
  </ul>
  <ul>

  </ul>

  <div class="card-footer">
    <p>
    <%= link_to '詳細', salon, class: "links_to" %> |
    <%= link_to '編集', edit_salon_path(salon), class: "links_to" %> |
    <%= link_to '削除', salon, method: :delete, data: { confirm: '削除します。よろしいですか?' }, class: "links_to" %>
    </p>
  </div>
</div>
<% end %>
</div>

app/views/salons/new.html.erb
<h1>New Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Back', salons_path %>

app/views/salons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @salon.image.attached? %>
    <p>
      <strong>Image:</strong>
      <br>
      <%= image_tag @salon.image %>
    </p>
  <% end %>
</p>

<p>
  <strong>Name:</strong>
  <%= @salon.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @salon.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @salon.phone %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @salon.comment %>
</p>

<p>
  <strong>Tokio:</strong>
  <%= @salon.tokio %>
</p>

<p>
  <strong>Ie:</strong>
  <%= @salon.ie %>
</p>

<p>
  <strong>Design:</strong>
  <%= @salon.design %>
</p>

<p>
  <strong>Straight:</strong>
  <%= @salon.straight %>
</p>

<%= link_to 'Edit', edit_salon_path(@salon) %> |
<%= link_to 'Back', salons_path %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_with model: @search do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.select :address, options_for_select(@address), include_blank: true %><br>

    <%= f.submit "Search" %>
<% end %>

<p><%= link_to "Back", '/salons' %></p>

app/views/searches/show.html.erb
<h1>Search Results</h1>
<p><%= link_to "Back", new_search_path %></p>



<% if @search.search_salon.empty? %>
    <p>検索に該当するサロンは見つかりませんでした</p>
<% else %>
    <p>見つかりました！</p>
<% end %>